### ISSUE TITLE
Supported only in intellij idea

### ISSUE THREAD

**Issue by dollarkillerx** [s-unscrupulous/idea_seat#1]
Hope to be compatible with webstorm goland clion

**Comment by Modificator** [comment]
https://github.com/s-unscrupulous/idea_seat/blob/9924551a5b59da191998911e5b65c7040b4238de/seat/resources/META-INF/plugin.xml#L11-L13
```xml
    <depends>com.intellij.modules.platform</depends>
    <depends>com.intellij.modules.lang</depends>
```
